# Loan Detector

## Importing libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sb

## Importing Data

In [2]:
df = pd.read_csv('raw_data/Loan_default.csv')
df2 = pd.read_csv('raw_data/Loan_approval.csv')

df.info()
df2.info()

df.head()

df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              50000 non-null  object
 1   age                      50000 non-null  int64
 2   occupation_status        50000 non-null  object
 3   years_employed           50000 non-null  float64
 4   annual_income            50000 non-null  int64
 5   credit_score             50000 non-null  int64
 6   credit_history_years     50000 non-null  float64
 7   savings_assets           50000 non-null  int64
 8   current_debt             50000 non-null  int64
 9   defaults_on_file         50000 non-null  int64
 10  delinquencies_last_2yrs  50000 non-null  int64
 11  derogatory_marks         50000 non-null  int64
 12  product_type             50000 non-null  object
 13  loan_intent              50000 non-null  object
 14  loan_amount              50000 non-null  int64
 15  interest_rate            50000 non-null  float64
 16  debt_to_income_ratio     50000 non-null  float64
 17  loan_to_income_ratio     50000 non-null  float64
 18  payment_to_income_ratio  50000 non-null  float64
 19  loan_status              50000 non-null  int64
dtypes: float64(6), int64(10), object(4)
memory usage: 7.6+ MB

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

## Cleaning Data

In [3]:
df = df.dropna()
df2 = df2.dropna()

df.head()
## In this particular scenario Data is already cleaned and doesn't need much alteration like splitting, cleaning of indivisual fields and so on

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [4]:
## Making the data consistent

df['EmploymentType'].value_counts()
df2['years_employed'] = df2['years_employed']*12
df2['credit_history_years'] = df2['credit_history_years']*12
df2.rename(columns={'years_employed': 'months_employed', 'credit_history_years':'credit_history_months'}, inplace=True)
df2.head()

,customer_id,age,occupation_status,months_employed,annual_income,credit_score,credit_history_months,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,206.4,25579,692,63.6,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,87.6,43087,627,42.0,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,13.2,20840,689,100.8,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,6.0,29147,692,117.6,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,150.0,63657,630,86.4,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [12]:
df['Default'].value_counts(normalize=True)
#df['Default'].value_counts()
df['Income'].describe()
df['CreditScore'].describe()

count    255347.000000
mean        574.264346
std         158.903867
min         300.000000
25%         437.000000
50%         574.000000
75%         712.000000
max         849.000000
Name: CreditScore, dtype: float64